baseURL = "https://blog.jayqi.com/"
languageCode = "en-us"
title = "Jay Qi"
theme = "hyde-hyde"

enableEmoji = true

[params]
    #author = "JYQ" # doesn't seem to do anything
    #title = "Blog" # doesn't seem to do anything
    description = "Blog"
    authorimage = "/img/jqi_photo.jpg"
    dateformat = "January 2, 2006"

    # sidebar, copyright & license
    copyright = "Jay Qi"
    #license = "CC BY-SA 4.0"
    #licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
    showBuiltWith = true

    # https://highlightjs.org
    highlightjs = true
    highlightjsstyle = "github"

## Social Accounts
[params.social]
    github = "jayqi"
    linkedin = "jayqi"
    twitter = "jayyqi"

## Main Menu
[[menu.main]]
        name = "Posts"
        weight = 100
        identifier = "posts"
        url = "/posts/"
